# Docker Compose for Permit API Development & Production
version: '3.8'

services:
  permit-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - API_KEYS=${API_KEYS}
      - MASTER_API_KEY=${MASTER_API_KEY}
    volumes:
      # Mount reference files for development
      - ./reference:/app/reference:ro
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # Optional: PostgreSQL for API key management (uncomment if needed)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: permit_api
  #     POSTGRES_USER: ${POSTGRES_USER:-permit_user}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-permit_pass}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
  # redis_data:
  # postgres_data:

networks:
  default:
    name: permit-api-network
